### ISSUE TITLE
Newlines stripped when reading STDIN

### ISSUE THREAD

**Issue by piotr-machura** [coloradocolby/fsrx#1]
## Description
When the file is provided as an argument, the newlines are handled correctly. But when `fsrx` reads from standard input the newlines are stripped away.

## To Reproduce
```sh
$ fsrx .bashrc # as expected
$ cat .bashrc | fsrx # a mess
```

## Expected behavior
The newline handling should be consistent between those two methods.

## Screenshots
![screenshot_54628065](https://user-images.githubusercontent.com/59394665/172460372-7f1f42db-2672-4f2d-941b-06fd6e0433da.png)

## Additional context

Fixing this would make it possible to use `fmt` to reflow incoming text to  a managable width, like so:
```sh
$ fmt -w 60 long_lines.txt | fsrx | less -R
```
Right now the newlines created by `fmt` are deleted.

**Comment by piotr-machura** [comment]
Just noticed that (some?) special characters at the end of lines are stripped as well. - notice the dissappearing `!` in the screenshot above.

Here is another screenshot with a line from  running `fsrx ~/.bashrc`, notice the unclosed parenthesis and double quotes:
![image](https://user-images.githubusercontent.com/59394665/172461580-e32c1913-f7b2-40bc-ba93-6070a71b441a.png)
Is this by design?

**Comment by coloradocolby** [comment]
@piotr-machura hmm I know this was working at some point, I must have added a regression. Looking now!

**Comment by coloradocolby** [comment]
all fixed! releasing now
