### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by yigitsever** [coloradocolby/fsrx#2]
Hello,

I started using the project (thank you!) and also packaged it to [Arch User Repository](https://aur.archlinux.org/packages/fsrx-git)

Arch Linux user can simply;

```
paru -S fsrx-git
```

Or using any other AUR helper they use. This can be added to the README.md if you'd like.

The `-git` tag (sorry if you already know this) says that the package tracks this repository directly. [AUR Submission Guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines) says that the `fsrx` package can be submitted to AUR when there's an official release on upstream (here). On a potential `fsrx`, the AUR package will download the release `.tar.gz` (instead of cloning the repository) and build the package using that.

Currently the repository is using _prereleases_, if you'd like you can start releasing full releases (feedback: as far as I can tell the program is stable and ready for use) and that can be packaged as well

Cheers

**Comment by THELEMITED** [comment]
> @yigitsever huh? So you are trying to release aur (Australia Reconnoiter) through a medium? Rx has a table called a cpanel that most - [1] software engineer ref.cp.mx[]()ref.cp.mx

**Comment by yigitsever** [comment]
@coloradocolby I (or someone else) would need to submit `fsrx` to AUR as well

**Comment by coloradocolby** [comment]
@yigitsever sounds good. I'll release tonight and send you a confirmation message here. Would you mind submitting `fsrx` for me?

**Comment by coloradocolby** [comment]
@yigitsever perfect! Just released v1.0.0 🎊
